Refracting wrapper to support latest libkiwix
kiwix/java-libkiwix pull request #20
Opened 2022-10-10 13:10 UTC by MohitMaliFtechiz

Fixes #19

2022-11-07 09:55 UTC, kelson42 requested changes
Add the github workflow to autopublish (look for example at `openzim/mwoffliner` or `openzim/sotoki` to look how it is done. Should be based on version tagging on `master`.

2022-11-09 17:01 UTC, mgautierfr requested changes
I haven't take a real look on the compilation/publication side.
But the Reader/Searcher side yes, and I disagree with it.

The `kiwix::Reader` doesn't exist anymore. The wrapper must now wrap `zim::Archive` so the wrapper must now be called `zimarchive` not `kiwixreader`. This is the same thing for `kiwixsearcher`.

The API of libzim and libkiwix are fundamentally different, the wrapper should follow the API of zim object, not stick to the old libkiwix api. If we don't we will face a lot of issues and difficulties.

2022-11-09 17:01 UTC, mgautierfr commented on android-libkiwixbuild/app/src/main/cpp/kiwixsearcher.cpp
> +}
Here you create a new search each time and you return a searchresultset.
But you must create the search only once and move the `getNextResult` function on the result set.
And I think we must not have a `getNextResult` we should have some kind of iterable structure (To define what it is in the java/kotlin word) and let the java/kotlin code iterate it.

2022-12-05 10:45 UTC, rgaudin commented
@MohitMaliFtechiz I will add redirects to nightlies so you don't have to find/guess date. I'll post back here once it's live.

2022-12-05 10:46 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz I will add redirects to nightlies so you don't have to find/guess date. I'll post back here once it's live.

Ok @rgaudin

2022-12-06 11:02 UTC, MohitMaliFtechiz commented
> 

hi @rgaudin ,

We need dedicated redirect url for every android architecture for both libzim and libkiwix and also for Linux architecture as well so we need 10 urls.
a) Libzim :- arm , arm64-v8a, x86 , x86_64 , Linux
b) Libkiwix:- arm , arm64-v8a, x86 , x86_64 , Linux

2022-12-06 11:05 UTC, rgaudin commented
I don't understand. This is what we currently have:

```
/nightly/libzim_macos-x86_64.tar.gz
/nightly/libzim_linux-x86_64.tar.gz
/nightly/libzim_android-arm.tar.gz
/nightly/libzim_android-arm64.tar.gz
/nightly/libzim_android-x86.tar.gz
/nightly/libzim_wasm-emscripten.tar.gz
/nightly/libzim_android-x86_64.tar.gz
```

```
/nightly/libkiwix_android-arm.tar.gz
/nightly/libkiwix_macos-x86_64.tar.gz
/nightly/libkiwix_android-x86.tar.gz
/nightly/libkiwix_android-x86_64.tar.gz
/nightly/libkiwix_linux-x86_64.tar.gz
/nightly/libkiwix_android-arm64.tar.gz
```

2022-12-06 11:07 UTC, MohitMaliFtechiz commented
> I don't understand. This is what we currently have:
> 
> ```
> /nightly/libzim_macos-x86_64.tar.gz
> /nightly/libzim_linux-x86_64.tar.gz
> /nightly/libzim_android-arm.tar.gz
> /nightly/libzim_android-arm64.tar.gz
> /nightly/libzim_android-x86.tar.gz
> /nightly/libzim_wasm-emscripten.tar.gz
> /nightly/libzim_android-x86_64.tar.gz
> ```
> 
> ```
> /nightly/libkiwix_android-arm.tar.gz
> /nightly/libkiwix_macos-x86_64.tar.gz
> /nightly/libkiwix_android-x86.tar.gz
> /nightly/libkiwix_android-x86_64.tar.gz
> /nightly/libkiwix_linux-x86_64.tar.gz
> /nightly/libkiwix_android-arm64.tar.gz
> ```

ok understood this will work.

2023-03-08 16:35 UTC, kelson42 commented
@MohitMaliDeveloper What should we do with this PR

2023-03-22 11:27 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz @ 2 weeks have passed and still no answer?!

We already have this changes on main branch , i think we can close this PR.

2023-03-22 11:27 UTC, closed without merging