Moving `java-libkiwix` to the new Maven repository with version code `1.0.0`
kiwix/java-libkiwix pull request #45
Opened 2023-07-18 09:53 UTC by MohitMaliFtechiz

Fixes #43 

* According to the conversation https://github.com/kiwix/java-libkiwix/issues/43#issuecomment-1639588336 we are moving our `java-libkiwix` to the new maven repo `org.kiwix.libkiwix` with version code `1.0.0`.
* Updated the source of `libkiwix` and `libzim` `.so` files from download.kiwix.org/release instead of using nightly builds.
* Introduced new variables for specifying the versions of `libkiwix` and `libzim`, to make the dynamic URL that retrieves the `.so` files from the release repositories.
* Modified the `README.md` file to emphasize the importance of updating the version before building the bindings.

2023-07-18 10:33 UTC, kelson42 requested changes
#43 Should be fixed here at the same time IMO:
* Use a gradle variable for bot libzim and libkiwix version
* Use the new variable created to create dynamically URLs for downloading (only for releases) from download.kiwix.org/release/libkiwix/ and download.openzim.org/release/libzim/
* Please update `README.md`

2023-07-18 14:13 UTC, kelson42 commented
@MohitMaliFtechiz I was not expecting instructions in Readme.md.... but update of badge code...

2023-07-19 05:57 UTC, MohitMaliFtechiz commented
@kelson42, I have updated the badge code in the README.md file. Currently, it will show as "not found" (https://img.shields.io/maven-central/v/org.kiwix.libkiwix/libkiwix) because we have not yet published the artifact on Maven. Once we publish the artifact on Maven, it will start displaying correctly in the badge.

2023-07-19 05:59 UTC, kelson42 commented
@MohitMaliFtechiz What is left to do on Maven, on Github, to be able to publish under this new name?

2023-07-19 06:03 UTC, MohitMaliFtechiz commented
> @MohitMaliFtechiz What is left to do on Maven, on Github, to be able to publish under this new name?

We do not need to change anything on Maven or GitHub, we can directly publish the artifact with the current CI with this new name.

2023-07-19 09:21 UTC, mgautierfr approved these changes
Seems good to me.

2023-07-19 09:21 UTC, merged